#!/bin/bash

pyuic4 -o contents/code/configui.py contents/ui/app-config.ui || exit $?
pyuic4 -o contents/code/emailui.py contents/ui/email.ui || exit $?

#overwrite images.qrc
QRCFILE=contents/code/images.qrc
echo "<RCC>" > $QRCFILE
echo '  <qresource prefix="/images">' >> $QRCFILE
for f in contents/images/*.png
do
    echo "    <file alias='$(basename $f)'>../images/$(basename $f)</file>" >> $QRCFILE
done
echo '  </qresource>' >> $QRCFILE
echo '</RCC>' >>$QRCFILE

pyrcc4 -o contents/code/images_rc.py contents/code/images.qrc || exit $?

rm shareit-plasmoid.plasmoid
zip -r shareit-plasmoid.plasmoid .
plasmapkg -u shareit-plasmoid.plasmoid && plasmoidviewer ShareIt-Plasmoid
