application: file-sharer
version: 1
runtime: python
api_version: 1
 
handlers:
- url: /paste
  script: paste.py

- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /.*
  script: show.py

